name = "DomainGistry"
uuid = "8669e32c-d706-11e9-0621-07ef2e9d41a8"
authors = ["JCharis <jcharistech@gmail.com>"]
version = "0.1.0"

[compat]
julia = "≥ 0.7.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
